# Docker Compose configuration for Recipe & Ingredient Management Database
# Run with: docker-compose up -d
# Access PgAdmin at: http://localhost:8080 (admin@admin.com / admin)
# Database connection: Host=localhost, Port=5432, Database=mfbdb, User=mfb, Password=mfb_pwd

services:
  # PostgreSQL 16 database server
  postgres:
    image: postgres:16
    container_name: mfb_postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # No authentication required
      POSTGRES_DB: mfbdb              # Our application database
    ports:
      - "5432:5432"                   # Expose PostgreSQL port to host
    volumes:
      - ./db/init/001_initial_schema.sql:/docker-entrypoint-initdb.d/001_initial_schema.sql:ro  # Schema only
      - mfb_pgdata:/var/lib/postgresql/data        # Persistent database storage

  # PgAdmin4 web interface for database management
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: mfb_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Login email for PgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin            # Login password for PgAdmin
    ports:
      - "8080:80"                     # Expose PgAdmin web interface
    depends_on:
      - postgres                      # Ensure PostgreSQL starts first

# Named volumes for data persistence
volumes:
  mfb_pgdata:                         # PostgreSQL data storage volume
