# Docker Compose configuration for Recipe & Ingredient Management Database
# Run with: docker-compose up -d
# Access PgAdmin at: http://localhost:8080 (admin@admin.com / admin)
# Database connection: Host=localhost, Port=5432, Database=mfbdb, User=mfb, Password=mfb_pwd

services:
  # PostgreSQL 16 database server
  postgres:
    image: postgres:16
    container_name: mfb_postgres
    environment:
      POSTGRES_USER: mfb              # Database user for application
      POSTGRES_PASSWORD: mfb_pwd      # Password for database user
      POSTGRES_DB: mfbdb              # Initial database name
    ports:
      - "5432:5432"                   # Expose PostgreSQL port to host
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro  # Auto-run SQL scripts on first startup
      - ./db/performance_scripts:/performance_scripts:ro  # Performance scripts (read-only, not auto-run)
      - mfb_pgdata:/var/lib/postgresql/data        # Persistent database storage

  # PgAdmin4 web interface for database management
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: mfb_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com     # Login email for PgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin            # Login password for PgAdmin
    ports:
      - "8080:80"                     # Expose PgAdmin web interface
    volumes:
      - mfb_pgadmin_data:/var/lib/pgadmin        # Persistent pgAdmin data storage
      - ./pgadmin_config/servers.json:/pgadmin4/servers.json:ro # Pre-configure database server
    depends_on:
      - postgres                      # Ensure PostgreSQL starts first

# Named volumes for data persistence
volumes:
  mfb_pgdata:                         # PostgreSQL data storage volume
  mfb_pgadmin_data:                   # PgAdmin data storage volume
