name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore DbClient.sln
    
    - name: Build
      run: dotnet build DbClient.sln --no-restore --configuration Release
    
    - name: Test
      run: dotnet test DbClient.sln --no-build --configuration Release --verbosity normal